import QRCode from 'qrcode';
import {MAP_INFO,createMap} from '../../shared/maps.js';
import {DEFAULT_RULES,VERSION,validateRules,type Rules,type Player,type Snapshot,type GameResult} from '../../shared/types.js';
import {DT,makePlayer,stepPlayer} from '../../shared/physics.js';
import {SceneRenderer} from './art.js';
import {Controls} from './input.js';
import {Connection,type Credentials} from './network.js';
import {styles} from './styles.js';
import {FinishNotice} from './finish-notice.js';
export type LumiConfig={title?:string;description?:string;theme?:'light'|'night';accent?:string;participant?:{id:string;name:string};activityId?:string;map?:number;rules?:Partial<Rules>;serverUrl?:string;joinBaseUrl?:string;storageKey?:string;onReady?:(s:Snapshot)=>void;onStart?:(s:Snapshot)=>void;onEnd?:(r:GameResult)=>void;onResult?:(r:GameResult)=>void};
export type LumiAPI={version:string;capabilities:readonly string[];start:()=>void;stop:()=>void;restart:()=>void;destroy:()=>void;practice:()=>void;getState:()=>Snapshot|null};
const escape=(value:unknown)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function mountLumiRun(container:HTMLElement,config:LumiConfig={}):LumiAPI {
 const host=document.createElement('div');container.append(host);const root=host.attachShadow({mode:'open'});const abort=new AbortController();
 let mapId=config.map||1,rules:Rules=validateRules(config.rules),map=createMap(mapId,rules.duration),screen='home',practice=false,paused=false,destroyed=false,practiceTick=0,local=makePlayer('practice',config.participant?.name||'루미'),snapshot:Snapshot|null=null,role:'host'|'player'|null=null,credentials:Credentials|null=null,lastPhase='',lastMatch='',seq=0,spectate='',lastRoster='',lastNet=0,acc=0,lastFrame=performance.now(),resultShown='',quality=false;
 const delivered=new Set<string>();const key=`lumi:${config.storageKey||config.activityId||'standalone'}`;const stored=sessionStorage.getItem(key);let saved:Credentials|null=null;try{saved=stored?JSON.parse(stored):null;}catch{}
 let lastRosterPaint=0;let predictedTick=0,snapshotAt=performance.now();let previousPlayers=new Map<string,Player>();
 const serverUrl=config.serverUrl||`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/ws`;
 root.innerHTML=`<style>${styles}</style><main class="shell"><header class="topbar"><div class="brand"><div class="mark">✦</div><strong>루미 런</strong><span class="sub">LUMI RUN / LITTLE ADVENTURES</span></div><nav class="nav"><span class="status" id="connection">로컬 플레이 준비됨</span><button class="small" id="quality">가벼운 그래픽</button><button class="small" id="home">처음으로</button></nav></header>
 <section id="home-screen"><div class="intro"><div><div class="eyebrow">READY, SET, EXPLORE</div><h1 id="title"></h1><p id="description"></p></div><span class="badge">함께 달리는 모험 · 최대 30명</span></div><div class="main-grid"><div class="scene-card"><canvas class="hero-canvas" aria-label="초원과 탐험 로봇 루미의 맵 미리보기"></canvas><div class="scene-title"><div class="eyebrow" id="hero-theme">WORLD 01 / THE MEADOWS</div><h2 id="hero-name"></h2><p id="hero-desc"></p></div><span class="scene-tag" id="hero-difficulty">입문</span><div class="scene-bottom"><span>작은 발걸음으로, 더 멀리.</span><button id="practice">혼자 연습하기 ↗</button></div></div><aside class="entry"><div class="tabs"><button id="student-tab" class="active">학생 · 참가하기</button><button id="teacher-tab">교사 · 방 만들기</button></div><div id="student-entry"><h3>함께 달릴 준비됐나요?</h3><p>선생님이 알려준 참가 코드를 입력하세요.</p><form id="join-form"><label>내 이름<input id="name" maxlength="18" placeholder="친구들에게 보일 이름" autocomplete="off" required></label><label>참가 코드<input id="code" maxlength="6" pattern="[0-9]{6}" inputmode="numeric" placeholder="6자리 숫자" required></label><button class="primary" type="submit">모험에 참가하기 →</button></form></div><div id="teacher-entry" hidden><h3>우리 반의 작은 모험</h3><p>맵과 규칙을 고르고, 참가 코드를 나눠 주세요.</p><div class="mode-count"><label>경기 방식<select id="preset"><option value="race">먼저 도착한 사람 보상</option><option value="last">꼴찌 선정</option></select></label><label>몇 명<input id="reward-count" type="number" min="1" max="30" value="1"></label></div><button id="create" class="primary">새 참가방 만들기 →</button><p class="hint">방을 만든 뒤 세부 규칙을 바꿀 수 있어요.</p></div><button id="resume" class="small" ${saved?'':'hidden'}>이전 참가방 다시 연결</button><div class="entry-note">설치 없이 브라우저에서 함께해요.<br>방향키로 이동하고, 스페이스로 점프!</div></aside></div><div class="section-head"><h3>어디로 떠나볼까요?</h3><span>5개의 세계 · 5단계 난이도</span></div><div class="maps" id="maps"></div></section>
 <section id="room-screen" hidden><div class="room-header"><div><div class="eyebrow">OUR LITTLE ADVENTURE</div><h2 id="room-title">우리 반 모험 준비</h2></div><span class="badge" id="room-phase">참가자를 기다리는 중</span></div><div class="room-layout"><aside class="panel" id="teacher-settings"><h3>이번 모험</h3><form id="settings"><label>맵<select name="map">${MAP_INFO.map(m=>`<option value="${m.id}">${m.name} · ${m.difficulty}</option>`).join('')}</select></label><div class="mode-count"><label>경기 방식<select name="mode"><option value="race">먼저 도착한 사람 보상</option><option value="last">꼴찌 선정</option></select></label><label>몇 명<input name="count" type="number" min="1" max="30" value="1"></label></div><h3>코스와 목숨</h3><div class="form-grid"><label>코스 길이<select name="duration"><option value="30">30초 코스</option><option value="45">45초 코스</option><option value="60">60초 코스</option><option value="90">90초 코스</option></select></label><label>목숨<select name="lives"><option value="0">무한</option><option value="1">1번</option><option value="3">3번</option><option value="5">5번</option></select></label></div><p class="hint">시간 제한 없이 달려요. 동점자는 공동 선정합니다.<br>누구든 시작을 누르면 현재 참가자가 함께 출발해요.</p><button type="submit" class="small">설정 적용</button></form></aside><div><div class="panel"><div class="join-box"><canvas id="qr" aria-label="학생 참가 링크 QR 코드"></canvas><div><div class="eyebrow">JOIN CODE</div><div class="room-code" id="room-code"></div><label class="hint">참가 주소 (휴대폰은 같은 Wi-Fi)</label><select id="join-address" aria-label="참가 주소 선택"></select><div class="join-link" id="join-link"></div><button id="copy" class="small">참가 링크 복사</button></div></div><h3>함께 달리는 친구들 <span id="player-count">0</span></h3><div id="roster" class="players"></div><p id="empty-room" class="hint">다른 브라우저에서 참가 코드를 입력해 주세요.</p><div class="actions"><button id="start" class="primary">다 함께 시작 →</button><span id="ready" hidden></span><button id="lobby-practice">기다리며 연습</button></div><p class="hint" id="rule-summary"></p></div><div class="student-wait"><h2>출발 전, 이렇게 움직여요.</h2><p><span class="key">←</span><span class="key">→</span> 또는 A / D로 이동<br><span class="key">SPACE</span> 또는 ↑ / W로 점프</p><p class="hint">휴대폰을 가로로 돌려 주세요. 화면 아래 버튼을 두 손가락으로 누르세요.<br>산호색 깃발은 다시 출발할 체크포인트예요.<br>경기 중 입장하면 관전으로 함께할 수 있어요.</p></div></div></div></section>
 <section id="game-screen" class="game-focus" hidden><div class="play-wrap" tabindex="0" aria-label="루미 런 게임. 방향키 이동, 스페이스 점프"><canvas class="game-canvas"></canvas><div class="rotate-guide">휴대폰을 가로로 돌려 주세요 ↻<small>가로 화면에서 앞쪽 장애물과 조작 버튼이 더 잘 보여요.</small></div><div class="hud"><div class="hud-card"><strong id="play-map"></strong><div id="play-state">연습 중</div><div class="progress"><i id="progress"></i></div></div><div class="hud-card"><div class="timer" id="time">60</div><span id="time-label">남은 시간</span></div><div class="hud-actions"><button id="pause" class="small">일시정지</button><button id="fullscreen" class="small">전체화면</button><button id="back" class="small">연습 끝내기</button><button id="end" class="small danger">강제 종료</button></div></div><div class="overlay" id="overlay" hidden><div><strong id="overlay-title"></strong><span id="overlay-sub"></span></div></div><div class="controls"><div class="controls-group"><button data-control="left" aria-label="왼쪽으로 이동">←</button><button data-control="right" aria-label="오른쪽으로 이동">→</button></div><button data-control="jump" aria-label="점프">점프 ↑</button></div></div><div class="play-info"><span>이동 ← → / A D &nbsp; 점프 SPACE / ↑ / W</span><div><span id="fps">60 fps</span> · <select id="spectate" aria-label="관전할 선수"></select></div></div><div class="mobile-hint">휴대폰은 가로 모드로 플레이해 주세요. 두 손가락으로 이동과 점프를 함께 눌러요.</div><div id="race-roster" class="race-roster" aria-label="전체 참가자 진행 상황"></div></section>
 <section id="results-screen" class="results" hidden><div class="result-banner"><div class="eyebrow">ADVENTURE COMPLETE</div><h2 id="result-title"></h2><p id="winners"></p><p id="reason"></p></div><div class="panel"><div class="section-head" style="margin-top:0"><h3>우리의 모험 기록</h3><span id="end-reason"></span></div><div class="table-wrap"><table><thead><tr><th>순위</th><th>참가자</th><th>상태</th><th>완주 시간</th><th>최대 진행</th></tr></thead><tbody id="result-rows"></tbody></table></div><p class="hint" id="ties"></p><div class="actions"><button id="restart" class="primary">같은 방에서 재경기</button><button id="download">결과 JSON 저장</button><button id="result-home">처음으로</button></div></div></section>
 <footer class="footer"><span>✦ LUMI RUN &nbsp; 작은 모험을 함께 나누는 시간</span><span><a href="/lesson-a.html">샘플 강의 01</a> &nbsp; / &nbsp; <a href="/lesson-b.html">샘플 강의 02</a> &nbsp; · &nbsp; v${VERSION}</span></footer><div id="toast" class="toast" role="status" hidden></div></main>`;
 const $=<T extends HTMLElement=HTMLElement>(id:string)=>root.querySelector<T>(`#${id}`)!;
 const on=(id:string,event:string,fn:EventListener)=>$(id).addEventListener(event,fn,{signal:abort.signal});
 $('title').textContent=config.title||'작은 모험, 함께 달리면 더 즐거워요.';$('description').textContent=config.description||'루미와 함께 달리고, 뛰어넘고, 우리 반의 다음 주인공을 만나보세요.';
 if(config.accent&&/^#[0-9a-f]{6}$/i.test(config.accent))host.style.setProperty('--accent',config.accent);
 if(config.theme==='night')host.style.setProperty('--paper','#e7eddf');
 $<HTMLInputElement>('name').value=config.participant?.name||'';$<HTMLInputElement>('name').readOnly=!!config.participant;$<HTMLSelectElement>('preset').value=rules.mode;$<HTMLInputElement>('reward-count').value=String(rules.count);const query=new URLSearchParams(location.search);$<HTMLInputElement>('code').value=query.get('room')||'';
 const hero=new SceneRenderer(root.querySelector('.hero-canvas')!);const renderer=new SceneRenderer(root.querySelector('.game-canvas')!);const surface=root.querySelector<HTMLElement>('.play-wrap')!;const controls=new Controls(root,surface);
 const finishNotice=new FinishNotice(surface,{retry:()=>beginPractice(),next:()=>{if(!snapshot&&mapId<5){mapId++;map=createMap(mapId,rules.duration);updateHero();beginPractice();}},exit:()=>{practice=false;finishNotice.reset();show(snapshot?'room':'home');}});
 let toastTimer:ReturnType<typeof setTimeout>;function toast(message:string){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6000);}
 const net=new Connection(serverUrl,receive,s=>$('connection').textContent=s,toast,c=>{credentials=c;role=c.role;sessionStorage.setItem(key,JSON.stringify(c));saved=c;});
 function show(next:string){screen=next;for(const s of ['home','room','game','results'])$(s+'-screen').hidden=s!==next;controls.clear();if(next==='game')surface.focus({preventScroll:true});}
 function updateHero(){const info=MAP_INFO.find(m=>m.id===mapId)!;$('hero-name').textContent=info.name;$('hero-desc').textContent=info.description;$('hero-difficulty').textContent=info.difficulty;$('hero-theme').textContent=`WORLD ${String(mapId).padStart(2,'0')} / ${['THE MEADOWS','SKY GARDENS','THE DESERT','CRYSTAL CAVES','STARLIGHT WORKS'][info.theme]}`;root.querySelectorAll<HTMLElement>('.map-card').forEach(b=>{b.classList.toggle('selected',Number(b.dataset.map)===mapId);b.setAttribute('aria-pressed',String(Number(b.dataset.map)===mapId));});hero.camera=80;}
 $('maps').innerHTML=MAP_INFO.map(m=>`<button class="map-card" data-map="${m.id}" aria-label="${m.name} 선택"><span class="map-num">${String(m.id).padStart(2,'0')}</span><canvas aria-hidden="true"></canvas><div class="map-info"><strong>${m.name}</strong><small>${m.difficulty} · ${['초원','공중정원','사막','수정동굴','별빛공장'][m.theme]}</small></div></button>`).join('');
 root.querySelectorAll<HTMLButtonElement>('.map-card').forEach(b=>{b.addEventListener('click',()=>{mapId=Number(b.dataset.map);map=createMap(mapId,rules.duration);updateHero();},{signal:abort.signal});});
 let thumbnailFrame=requestAnimationFrame(()=>root.querySelectorAll<HTMLElement>('.map-card').forEach(b=>{const c=b.querySelector('canvas')!;const rend=new SceneRenderer(c);const m=createMap(Number(b.dataset.map));const p=makePlayer('thumb','');p.x=1150;p.y=m.platforms.find(v=>p.x>=v.x&&p.x<=v.x+v.w)?.y||430;rend.render(m,[p],'thumb',1,{instant:true});}));updateHero();
 function beginPractice(){if(snapshot&&snapshot.phase!=='lobby'){toast('온라인 경기가 끝난 뒤 연습할 수 있어요.');return;}finishNotice.reset();practice=true;paused=false;$('pause').textContent='일시정지';practiceTick=0;local=makePlayer('practice',config.participant?.name||$<HTMLInputElement>('name').value||'루미');map=createMap(mapId,rules.duration);renderer.camera=0;show('game');updateGameButtons();}
 function updateGameButtons(){$('pause').hidden=!practice;$('back').hidden=!practice;$('end').hidden=practice||role!=='host';$('spectate').hidden=true;surface.querySelector<HTMLElement>('.controls')!.hidden=!practice&&role==='host';$('play-map').textContent=map.name;}
 function setTab(teacher:boolean){$('teacher-entry').hidden=!teacher;$('student-entry').hidden=teacher;$('teacher-tab').classList.toggle('active',teacher);$('student-tab').classList.toggle('active',!teacher);}
 on('teacher-tab','click',()=>setTab(true));on('student-tab','click',()=>setTab(false));on('practice','click',beginPractice);on('lobby-practice','click',beginPractice);
 on('join-form','submit',e=>{e.preventDefault();net.destroy();net.state=null;snapshot=null;net.connect({type:'join',code:$<HTMLInputElement>('code').value,name:config.participant?.name||$<HTMLInputElement>('name').value,id:config.participant?.id||crypto.randomUUID()});});
 on('create','click',()=>{net.destroy();net.state=null;snapshot=null;rules={...rules,mode:$<HTMLSelectElement>('preset').value as Rules['mode'],count:Number($<HTMLInputElement>('reward-count').value)};net.connect({type:'create',activityId:config.activityId||'',map:mapId,rules});});
 on('resume','click',()=>{if(saved){net.destroy();net.state=null;net.connect({...saved,type:'join'});}});
 const home=()=>{net.destroy();snapshot=null;role=null;practice=false;credentials=null;lastPhase='';show('home');$('connection').textContent='로컬 플레이 준비됨';$('resume').hidden=!saved;};on('home','click',home);on('result-home','click',home);
 on('back','click',()=>{practice=false;paused=false;show(snapshot?'room':'home');});on('pause','click',()=>{if(practice){paused=!paused;controls.clear();$('pause').textContent=paused?'계속하기':'일시정지';}});
 on('fullscreen','click',()=>{if(document.fullscreenElement)void document.exitFullscreen();else if($('game-screen').requestFullscreen)void $('game-screen').requestFullscreen().catch(()=>toast('이 브라우저에서는 전체화면을 지원하지 않아요. 지금 화면에서도 플레이할 수 있어요.'));else toast('휴대폰을 가로로 돌려 플레이해 주세요.');});
 on('ready','click',()=>{const p=snapshot?.players.find(p=>p.id===credentials?.id);net.send({type:'ready',ready:!p?.ready});});on('start','click',()=>net.send({type:'start'}));on('end','click',()=>net.send({type:'end'}));on('restart','click',()=>net.send({type:'restart'}));
 on('settings','submit',e=>{e.preventDefault();const data=new FormData($<HTMLFormElement>('settings'));net.send({type:'settings',map:Number(data.get('map')),rules:{...rules,mode:data.get('mode'),duration:Number(data.get('duration')),lives:Number(data.get('lives')),count:Number(data.get('count'))}});});
 on('spectate','change',()=>{spectate=$<HTMLSelectElement>('spectate').value;renderer.camera=0;});on('quality','click',()=>{quality=!quality;renderer.low=hero.low=quality;$('quality').textContent=quality?'그래픽: 가볍게':'가벼운 그래픽';});
 let joinUrl='';async function updateQR(){const base=$<HTMLSelectElement>('join-address').value||location.origin;const u=new URL(config.joinBaseUrl||'/',base);u.searchParams.set('room',snapshot!.code);joinUrl=u.href;$('join-link').textContent=joinUrl;await QRCode.toCanvas($<HTMLCanvasElement>('qr'),joinUrl,{width:150,margin:1,color:{dark:'#204844',light:'#fffdf7'}});}
 on('join-address','change',()=>void updateQR());on('copy','click',()=>{if(navigator.clipboard)void navigator.clipboard.writeText(joinUrl).then(()=>toast('참가 링크를 복사했어요.')).catch(()=>toast(`이 주소를 복사해 주세요: ${joinUrl}`));else toast(`이 주소를 복사해 주세요: ${joinUrl}`);});
 on('download','click',()=>{if(!snapshot?.result)return;const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot.result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`lumi-${snapshot.matchId}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 function syncSettings(){const f=$<HTMLFormElement>('settings');for(const [k,v] of Object.entries({...rules,map:mapId})){const el=f.elements.namedItem(k) as HTMLInputElement|null;if(!el)continue;if(el.type==='checkbox')el.checked=Boolean(v);else el.value=String(v);} }
 function receive(s:Snapshot){
  const before=snapshot;previousPlayers=new Map(before?.players.map(p=>[p.id,p])||[]);snapshotAt=performance.now();snapshot=s;const transition=s.phase!==lastPhase||s.matchId!==lastMatch;predictedTick=transition?s.tick:Math.max(s.tick,Math.min(s.tick+6,predictedTick));mapId=s.map;rules=s.rules;if(map.id!==mapId||before?.rules.duration!==rules.duration)map=createMap(mapId,rules.duration);
  const me=s.players.find(p=>p.id===credentials?.id);if(me){seq=Math.max(seq,me.ack);if(!practice){const dx=me.x-local.x,dy=me.y-local.y;const hard=transition||Math.abs(dx)>90||Math.abs(dy)>80||me.status!==local.status||me.respawn>0;local={...me,x:hard?me.x:local.x+dx*.45,y:hard?me.y:local.y+dy*.45};}}
  if(transition){lastPhase=s.phase;lastMatch=s.matchId;practice=false;paused=false;controls.clear();renderer.camera=0;
   if(s.phase==='lobby'){show('room');syncSettings();$('teacher-settings').hidden=role!=='host';$('start').hidden=false;$('ready').hidden=true;$('room-code').textContent=s.code;
    $<HTMLSelectElement>('join-address').innerHTML=`<option value="${escape(location.origin)}">이 컴퓨터 주소</option>`;
    void fetch(new URL('/api/local',serverUrl.replace(/^ws/,'http'))).then(r=>r.json()).then(async({addresses}:{addresses:string[]})=>{if(destroyed||!snapshot)return;for(const address of addresses){const opt=document.createElement('option');opt.value=address;opt.textContent=`같은 Wi-Fi · ${address}`;$('join-address').append(opt);}if(addresses.length)$<HTMLSelectElement>('join-address').value=addresses[0];await updateQR();}).catch(()=>void updateQR());config.onReady?.(s);
   }else if(s.phase==='countdown'||s.phase==='running'){show('game');updateGameButtons();if(s.phase==='running')config.onStart?.(s);}
   else if(s.phase==='results'&&s.result){show('results');displayResult(s.result);}
  }
  if(s.phase==='lobby'){
   const roster=s.players.map(p=>`${p.id}:${p.connected}:${p.ready}`).join('|');if(roster!==lastRoster){lastRoster=roster;$('roster').innerHTML=s.players.map(p=>`<div class="player-chip"><span class="avatar">${escape(p.name.slice(0,1))}</span><span>${escape(p.name)}</span><span class="dot">${!p.connected?'끊김':'● 참가'}</span></div>`).join('');}
   $('player-count').textContent=String(s.players.filter(p=>p.connected).length);$('empty-room').hidden=s.players.length>0;$('ready').textContent=me?.ready?'준비 취소':'준비 완료';$('room-title').textContent=role==='host'?'우리 반 모험 준비':'루미와 출발을 기다려요';$('rule-summary').textContent=`${map.name} · ${rules.duration}초 길이 · 제한 시간 없음 · 목숨 ${rules.lives||'무한'} · ${rules.mode==='race'?'먼저 도착':'꼴찌'} ${rules.count}명 · ${s.hostConnected?'교사 연결됨':'교사 재접속 대기'}`;
  }
  const ids=s.players.filter(p=>p.status==='active').map(p=>p.id).join(',');if($('spectate').dataset.ids!==ids){$('spectate').dataset.ids=ids;$('spectate').innerHTML=`<option value="">자동 관전</option>`+s.players.filter(p=>p.status==='active').map(p=>`<option value="${escape(p.id)}">${escape(p.name)}</option>`).join('');$<HTMLSelectElement>('spectate').value=spectate;}
 }
 function displayResult(r:GameResult){
  resultShown=r.matchId;$('result-title').textContent=r.rules.text||'모험이 끝났어요!';$('winners').textContent=r.selectedIds.length?r.players.filter(p=>r.selectedIds.includes(p.id)).map(p=>p.name).join(', '):'이번 경기의 선정 대상이 없어요.';$('reason').textContent=r.selectionReason;$('end-reason').textContent={normal:'정상 종료',timeout:'제한 시간 종료',teacher:'교사가 종료'}[r.endReason];$('ties').textContent=r.tieHandling+' · 연결이 끊긴 참가자는 선정에서 제외됩니다.';
  const labels:Record<string,string>={active:'미완주',finished:'완주',eliminated:'탈락',spectator:'관전자',disconnected:'연결 중단'};
  $('result-rows').innerHTML=r.players.map(p=>`<tr><td>${p.rank??'—'}</td><td>${escape(p.name)}${r.selectedIds.includes(p.id)?' ✦':''}</td><td>${p.bot?'개발용 봇':labels[p.status]||p.status}</td><td>${p.finishTime===null?'—':p.finishTime.toFixed(2)+'초'}</td><td>${Math.max(0,Math.round(p.progress/10))} m</td></tr>`).join('');$('restart').hidden=role!=='host';
  if(!delivered.has(r.matchId)){delivered.add(r.matchId);config.onEnd?.(r);config.onResult?.(r);}
 }
 function frame(now:number){if(destroyed)return;const elapsed=Math.min((now-lastFrame)/1000,.1);lastFrame=now;acc+=elapsed;
  if(screen==='home'){const p=makePlayer('hero','루미');p.x=hero.width*.44+80;p.y=430;p.vx=0;hero.render(map,[p],'hero',now/1000,{preview:true});}
  if(screen==='game'){
   const input=controls.value();let steps=0;while(acc>=DT){acc-=DT;steps++;if(practice&&!paused){practiceTick++;stepPlayer(local,input,map,{...rules,mode:'race'},practiceTick,true);}else if(snapshot?.phase==='running'&&role==='player'){stepPlayer(local,input,map,rules,++predictedTick);}}
   if(practice&&steps>0)controls.consumeJump();
   if(!practice&&snapshot?.phase==='running'&&now-lastNet>33){lastNet=now;net.send({type:'input',...input,seq:++seq});controls.consumeJump();}
   const me=snapshot?.players.find(p=>p.id===credentials?.id);finishNotice.update(practice?local:me,practice,snapshot?.matchId||'practice',map.name,now,!snapshot&&mapId<5);
   const watching=!practice&&role==='host';const leader=snapshot?.players.filter(p=>p.connected&&p.status!=='spectator').sort((a,b)=>b.x-a.x)[0];const target=practice?local:watching?leader:local;
   const alpha=Math.min(1,(now-snapshotAt)/50);const players=practice?[local]:(snapshot?.players.map(p=>{if(p.id===local.id&&!watching)return local;const old=previousPlayers.get(p.id);return old&&Math.abs(old.x-p.x)<100&&Math.abs(old.y-p.y)<100?{...p,x:old.x+(p.x-old.x)*alpha,y:old.y+(p.y-old.y)*alpha}:p;})||[]);const time=practice?practiceTick/60:(snapshot?.tick||0)/60;
   const renderTime=time+(!practice&&snapshot?.phase==='running'?Math.min(.1,(now-snapshotAt)/1000):0);renderer.render(map,players,target?.id||'',renderTime,{chase:practice?-500:snapshot?.chase??-500,celebration:finishNotice.age(now)});
   const practiceFinished=practice&&local.status==='finished';$('pause').hidden=!practice||practiceFinished;
   $('time').textContent=practiceFinished?`${(local.finishTick!/60).toFixed(2)}`:practice?'∞':time.toFixed(1);$('time-label').textContent=practiceFinished?'완주 기록 (초)':practice?'자유 연습':'경과 시간 · 제한 없음';$('progress').style.width=`${Math.min(100,(target?.progress||0)/map.finish*100)}%`;$('fps').textContent=`${renderer.fps} fps`;
   $('play-state').textContent=practiceFinished?'완주! 다음 모험을 선택해 주세요':practice?'자유 연습 · 무한 재도전':watching?(snapshot?.players.every(p=>p.status!=='active')?'도전 종료 · 강제 종료 후 재경기할 수 있어요':`선두 · ${target?.name||'대기 중'}`):local.status==='eliminated'?'목숨을 모두 사용했어요 · 결과를 기다려 주세요':local.status==='finished'?'완주! 친구들이 도전하고 있어요':`${local.name} · 목숨 ${rules.lives===0?'무한':local.lives}`;
   if(!practice&&snapshot&&now-lastRosterPaint>200){lastRosterPaint=now;$('race-roster').innerHTML=snapshot.players.filter(p=>p.status!=='spectator').map(p=>`<span class="race-chip ${p.id===credentials?.id?'me':''}" style="--progress:${Math.min(100,p.progress/map.finish*100).toFixed(1)}%">${escape(p.name)} · ${p.status==='finished'?'완주':p.status==='eliminated'?'탈락':!p.connected?'끊김':Math.round(p.x/10)+'m'}</span>`).join('');}$('race-roster').hidden=practice;
   const countdown=snapshot?.phase==='countdown'&&!practice,respawning=(target?.respawn||0)>0&&!watching;const overlay=paused||countdown||respawning;
   $('overlay').hidden=!overlay;$('overlay-title').textContent=paused?'잠깐 쉬어요':countdown?String(Math.max(1,Math.ceil(snapshot!.countdown/60))):'다시 도전!';$('overlay-sub').textContent=paused?'계속하기를 누르면 이어서 달려요':countdown?'방향키로 이동 · 스페이스로 점프':'가까운 깃발에서 다시 출발해요';
  }else acc=0;
  request=requestAnimationFrame(frame);
 }
 let request=requestAnimationFrame(frame);
 return {version:VERSION,capabilities:['mount','practice','start','stop','restart','destroy','server-results','reconnect','spectate','touch','30-45-60-90-courses','5-maps','player-start','nicknames'],start:()=>net.send({type:'start'}),stop:()=>net.send({type:'end'}),restart:()=>net.send({type:'restart'}),practice:beginPractice,getState:()=>snapshot,destroy:()=>{destroyed=true;cancelAnimationFrame(request);cancelAnimationFrame(thumbnailFrame);clearTimeout(toastTimer);abort.abort();controls.destroy();finishNotice.destroy();net.destroy();host.remove();}};
}
